export enum QueryState {
  WAITING_FOR_PREREQUISITES = 'WAITING_FOR_PREREQUISITES',
  QUEUED = 'QUEUED',
  WAITING_FOR_RESOURCES = 'WAITING_FOR_RESOURCES',
  DISPATCHING = 'DISPATCHING',
  PLANNING = 'PLANNING',
  STARTING = 'STARTING',
  RUNNING = 'RUNNING',
  FINISHING = 'FINISHING',
  FINISHED = 'FINISHED',
  FAILED = 'FAILED',
}

export enum StageExecutionState {
  PLANNED = 'PLANNED',
  SCHEDULING = 'SCHEDULING',
  FINISHED_TASK_SCHEDULING = 'FINISHED_TASK_SCHEDULING',
  SCHEDULING_SPLITS = 'SCHEDULING_SPLITS',
  SCHEDULED = 'SCHEDULED',
  RUNNING = 'RUNNING',
  FINISHED = 'FINISHED',
  CANCELED = 'CANCELED',
  ABORTED = 'ABORTED',
  FAILED = 'FAILED',
}

export enum RuntimeUnit {
  NONE = 'NONE',
  NANO = 'NANO',
  BYTE = 'BYTE',
}

export enum ErrorType {
  USER_ERROR = 'USER_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  INSUFFICIENT_RESOURCES = 'INSUFFICIENT_RESOURCES',
  EXTERNAL = 'EXTERNAL',
}

export enum QueryType {
  CREATE_TABLE_AS_SELECT = 'CREATE_TABLE_AS_SELECT',
  INSERT = 'INSERT',
  QUERY = 'QUERY',
  CREATE_VIEW = 'CREATE_VIEW',
  CREATE_TABLE = 'CREATE_TABLE',
  UNSUPPORTED = 'UNSUPPORTED',
}
